version: "3.7"

services:
  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome-node:
    image: seleniarm/node-chromium:latest
    container_name: selenium-node-chrome
    depends_on:
      - selenium-hub
    shm_size: '2gb'
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3  # Tells this node it can run 3 browsers at the same time
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

  firefox-node:
    image: seleniarm/node-firefox:latest
    container_name: selenium-node-firefox
    depends_on:
      - selenium-hub
    shm_size: '2gb'
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3  # Tells this node it can run 3 browsers at the same time
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true